const STORE_API = '/api/store';
const FALLBACK_PRODUCTS = [
 {id:'thermocouple-aria',slug:'thermocouple-aria',name:'شیر ترموکوبل آریا با میکروسوئیچ',category:'قطعات اجاق گاز',price:16500000,stock:5,images:['/assets/products/placeholder.svg'],description:'محصول نمونه برای راه‌اندازی ساختار فروشگاه. پس از آماده‌شدن مدیریت محصولات، اطلاعات واقعی جایگزین می‌شود.',specs:{'برند':'آریا','نوع':'شیر ترموکوبل','کاربرد':'اجاق گاز'}},
 {id:'igniter-wire-set',slug:'igniter-wire-set',name:'سیم فندک ست ۵ شعله',category:'قطعات اجاق گاز',price:7500000,stock:10,images:['/assets/products/placeholder.svg'],description:'محصول نمونه.',specs:{'نوع':'سیم فندک','تعداد':'ست ۵ شعله'}},
 {id:'pilot-wire',slug:'pilot-wire',name:'سیم ترموکوبل پلوپز فیشی',category:'قطعات اجاق گاز',price:3500000,stock:8,images:['/assets/products/placeholder.svg'],description:'محصول نمونه.',specs:{'نوع':'سیم ترموکوبل','اتصال':'فیشی'}}
];
let PRODUCTS = FALLBACK_PRODUCTS;
const CART_KEY='apadana_cart_v1';
const toman=n=>new Intl.NumberFormat('fa-IR').format(Math.round(n/10))+' تومان';
const num=n=>new Intl.NumberFormat('fa-IR').format(n);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch{return[]}}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll('#cartCount').forEach(e=>e.textContent=num(n))}
function addToCart(id,qty=1){const p=PRODUCTS.find(x=>x.id===id);if(!p||p.stock<1)return;const c=getCart(),i=c.findIndex(x=>x.id===id);if(i<0)c.push({id,qty:Math.min(qty,p.stock)});else c[i].qty=Math.min(c[i].qty+qty,p.stock);saveCart(c);alert('محصول به سبد خرید اضافه شد.')}
function productCard(p){const stock=p.stock>0?(p.stock<=3?`فقط ${num(p.stock)} عدد باقی مانده`:'موجود'): 'ناموجود';return `<article class="product-card"><a href="/store/product.html?slug=${encodeURIComponent(p.slug)}"><img class="product-image" src="${esc(p.images?.[0]||'/assets/products/placeholder.svg')}" alt="${esc(p.name)}" loading="lazy"></a><div class="product-body"><span class="product-category">${esc(p.category)}</span><h2 class="product-title"><a href="/store/product.html?slug=${encodeURIComponent(p.slug)}">${esc(p.name)}</a></h2><span class="stock ${p.stock?'ok':'out'}">${stock}</span><div class="price">${toman(p.price)} <small>قیمت</small></div><div class="card-actions"><a class="btn-outline" href="/store/product.html?slug=${encodeURIComponent(p.slug)}">جزئیات</a><button class="btn btn-call" type="button" onclick="addToCart('${p.id}')">افزودن</button></div></div></article>`}
async function loadProducts(){try{const r=await fetch(STORE_API+'/products');if(r.ok){const d=await r.json();if(Array.isArray(d.products)&&d.products.length)PRODUCTS=d.products}}catch{}}
function initMenu(){const t=document.getElementById('menuToggle'),n=document.getElementById('mainNav');if(!t||!n)return;t.onclick=()=>{const o=n.classList.toggle('open');t.classList.toggle('active',o);t.setAttribute('aria-expanded',String(o))};n.querySelectorAll('a').forEach(a=>a.onclick=()=>n.classList.remove('open'))}
async function initStore(){await loadProducts();const grid=document.getElementById('productGrid');if(!grid)return;const cat=document.getElementById('categoryFilter'),search=document.getElementById('productSearch');[...new Set(PRODUCTS.map(p=>p.category))].forEach(c=>cat.add(new Option(c,c)));const render=()=>{const q=search.value.trim().toLowerCase(),c=cat.value;const list=PRODUCTS.filter(p=>(!c||p.category===c)&&(!q||`${p.name} ${p.category}`.toLowerCase().includes(q)));grid.innerHTML=list.map(productCard).join('');document.getElementById('emptyState').hidden=!!list.length};search.oninput=render;cat.onchange=render;render()}
function initProduct(){const root=document.getElementById('productDetail');if(!root)return;const slug=new URLSearchParams(location.search).get('slug');const p=PRODUCTS.find(x=>x.slug===slug)||PRODUCTS[0];if(!p){root.innerHTML='<div class="empty-state">محصول پیدا نشد.</div>';return}document.title=`${p.name} | فروشگاه تأسیسات آپادانا`;document.getElementById('breadcrumbName').textContent=p.name;root.innerHTML=`<article class="product-detail"><div><img id="mainProductImage" class="gallery-main" src="${esc(p.images?.[0])}" alt="${esc(p.name)}">${(p.images||[]).length>1?`<div class="thumbs">${p.images.map((x,i)=>`<img class="thumb ${i?'':'active'}" src="${esc(x)}" alt="${esc(p.name)} - تصویر ${i+1}" onclick="document.getElementById('mainProductImage').src=this.src;document.querySelectorAll('.thumb').forEach(t=>t.classList.remove('active'));this.classList.add('active')">`).join('')}</div>`:''}</div><div class="detail-info"><span class="product-category">${esc(p.category)}</span><h1>${esc(p.name)}</h1><div class="detail-price">${toman(p.price)}</div><div class="detail-stock">${p.stock?'موجودی: '+num(p.stock)+' عدد':'ناموجود'}</div><p class="detail-description">${esc(p.description)}</p><div class="specs"><h2>مشخصات فنی</h2>${Object.entries(p.specs||{}).map(([k,v])=>`<div class="spec-row"><strong>${esc(k)}</strong><span>${esc(v)}</span></div>`).join('')}</div><div class="quantity"><label for="qty">تعداد</label><input id="qty" type="number" min="1" max="${p.stock}" value="1"></div><button class="btn btn-call" ${p.stock?'':'disabled'} onclick="addToCart('${p.id}',Number(document.getElementById('qty').value))">افزودن به سبد خرید</button></div></article>`;const ld={ '@context':'https://schema.org','@type':'Product',name:p.name,description:p.description,image:p.images,url:location.href,offers:{'@type':'Offer',priceCurrency:'IRR',price:String(p.price*10),availability:p.stock?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:location.href}};const s=document.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify(ld);document.head.appendChild(s)}
function initCart(){const root=document.getElementById('cartPage');if(!root)return;const render=()=>{const c=getCart().map(x=>({...x,p:PRODUCTS.find(p=>p.id===x.id)})).filter(x=>x.p);if(!c.length){root.innerHTML='<div class="empty-state">سبد خرید شما خالی است.<br><br><a class="btn btn-call" href="/store/">مشاهده محصولات</a></div>';return}const total=c.reduce((s,x)=>s+x.p.price*x.qty,0);root.innerHTML=`<div class="cart-wrap"><table class="cart-table"><thead><tr><th>محصول</th><th>تعداد</th><th>قیمت</th><th>جمع</th><th></th></tr></thead><tbody>${c.map(x=>`<tr><td><div style="display:flex;gap:10px;align-items:center"><img class="cart-item-image" src="${esc(x.p.images[0])}" alt=""><span>${esc(x.p.name)}</span></div></td><td><div class="qty-control"><button onclick="changeQty('${x.id}',-1)">−</button><span>${num(x.qty)}</span><button onclick="changeQty('${x.id}',1)">+</button></div></td><td>${toman(x.p.price)}</td><td>${toman(x.p.price*x.qty)}</td><td><button class="btn-outline" onclick="removeCart('${x.id}')">حذف</button></td></tr>`).join('')}</tbody></table><div class="cart-total"><span>مجموع</span><span>${toman(total)}</span></div><div class="cart-actions"><a class="btn btn-call" href="/store/checkout.html">ثبت سفارش</a><a class="btn-outline" href="/store/">ادامه خرید</a></div></div>`};window.changeQty=(id,d)=>{const c=getCart(),i=c.findIndex(x=>x.id===id),p=PRODUCTS.find(x=>x.id===id);if(i<0)return;c[i].qty=Math.max(0,Math.min(p.stock,c[i].qty+d));if(!c[i].qty)c.splice(i,1);saveCart(c);render()};window.removeCart=id=>{saveCart(getCart().filter(x=>x.id!==id));render()};render()}
function initCheckout(){const form=document.getElementById('checkoutForm'),summary=document.getElementById('checkoutSummary');if(!form)return;const c=getCart().map(x=>({...x,p:PRODUCTS.find(p=>p.id===x.id)})).filter(x=>x.p);const total=c.reduce((s,x)=>s+x.p.price*x.qty,0);summary.innerHTML=`<h2>خلاصه سفارش</h2>${c.map(x=>`<div class="summary-row"><span>${esc(x.p.name)} × ${num(x.qty)}</span><strong>${toman(x.p.price*x.qty)}</strong></div>`).join('')}<div class="cart-total"><span>مجموع</span><span>${toman(total)}</span></div>`;form.onsubmit=async e=>{e.preventDefault();if(!c.length)return;const msg=document.getElementById('checkoutMessage');msg.textContent='در حال ثبت سفارش...';const order={customer:Object.fromEntries(new FormData(form)),items:c.map(x=>({productId:x.id,qty:x.qty})),total};try{const r=await fetch(STORE_API+'/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(order)});if(!r.ok)throw Error();const d=await r.json();if(d.paymentUrl)location.href=d.paymentUrl;else msg.textContent='سفارش ثبت شد. اتصال درگاه پس از قرارگیری اطلاعات درگاه فعال می‌شود.'}catch{msg.textContent='ثبت سفارش در حال حاضر از طریق نسخه نمایشی انجام نمی‌شود. پس از اتصال API فروشگاه فعال خواهد شد.'}}}
document.addEventListener('DOMContentLoaded',async()=>{initMenu();updateCartCount();await loadProducts();initStore();initProduct();initCart();initCheckout();const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear()});
